# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: PicoTechnology.Picoscope.Automotive.EA
PackageVersion: 7.2.19.8712
InstallerType: burn
Scope: machine
Protocols:
- picoauto
FileExtensions:
- pddata
- picoauto
ProductCode: '{5485aa25-6323-49f0-ad83-932b5b745}'
ReleaseDate: 2026-04-17
AppsAndFeaturesEntries:
- UpgradeCode: '{550419CA-B518-474B-82CD-2D407754CFBF}'
Installers:
- Architecture: x64
  InstallerUrl: https://www.picoauto.com/download/software/beta/PicoScope_7_Automotive_Early_Access_7.2.19.8712.x64.exe
  InstallerSha256: 62269D8CE41CB8D79565D42194CB09F12AE450D319937586689F99741542D2ED
ManifestType: installer
ManifestVersion: 1.10.0


